### ISSUE TITLE
Add Readme

### ISSUE THREAD

**Issue by EdGreen21** [ssciwr/predicTCR#34]
readme/help >> might want to think about how we do this best, whether a hosted webpage would suffice or whether we should start proper [readthedocs ](https://docs.readthedocs.io/en/stable/) documentation. 

Might need input from Kyle

**Comment by EdGreen21** [comment]
First draft attached to facilitate integration into website
[predicTCR_readme.md](https://github.com/user-attachments/files/18180118/predicTCR_readme.md)

**Comment by lkeegan** [comment]
About page content (https://predictcr.com/about) can now be edited as markdown in the admin settings tab.
