### ISSUE TITLE
Runners / Runner Jobs table output

### ISSUE THREAD

**Issue by EdGreen21** [ssciwr/predicTCR#47]
For diagnostics/justification to funders it would be useful to make changes to the `Runner Jobs` panel so that when exported it can be analysed to show how many people use the service, types of sample, total runtime etc. I would suggest the following changes:

1. `HOSTNAME `>> this doesn't seem very human readable, is it required? Can this be changed to reporter the `USER` submitting the job?
2. `RUNTIME` >> can this be formatted `mm:ss` to make it easier to collate
3. `ERROR MESSAGE` >> this needs syncing with the runner scripts under development, maybe add a default message 'unknown cause of failure' rather than blank>?
4. Add `TUMOR TYPE` and `SOURCE` >> I don't want to clutter the interface too much, but this is useful for us to understand what people are actually using the predicTCR for

**Comment by lkeegan** [comment]
Sure - I think the Samples admin panel is what you want for this, which has an entry for every sample with user, tumor type and source:

![image](https://github.com/user-attachments/assets/7b9030a8-7e91-45f7-983e-1738490df27f)

I can also add the runtime to this table.

(The runners tab is more of an admin tool to see / debug what is going on with the runners)
