### ISSUE TITLE
results upload

### ISSUE THREAD

**Issue by lkeegan** [ssciwr/predicTCR#6]
results from runner analysis script will be:

- csv file
- breakpoint between reactive/non-reactive rows in csv file
- visualisation of results
  - todo: this could either be 
    - generated as png/svg by the script (easier to modify in the future)
    - or the website could generate the visualization from the results directly

**Comment by EdGreen21** [comment]
if we get the TCR manufacturing paper out, then we could use this to drive academic interest towards our solution

**Comment by lkeegan** [comment]
Following today's discussion on uploading the results:

- the script
  - takes a `full_results` argument that specifies if the user should get partial or full results
  - puts generated result files into two folders:
    - `user_results/`
      - these files will be provided to the user from the website as a zipfile to download
    - `admin_results/`
      - these files will only be accessible by admins (also as a zip file)
      - should also contain logs for debugging failed runs

- the runner
  - passes the `full_results` argument to the script
  - zips & uploads the contents of the `user_results` folder for web access by the user
  - zips & uploads the contents of the `admin_results` folder for web access by admins
